/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ForestAnonymousAvatar: typeof import('./components/ForestAnonymousAvatar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PickupMoodModal: typeof import('./components/PickupMoodModal.vue')['default']
    PostCard: typeof import('./components/PostCard.vue')['default']
    PostListSkeleton: typeof import('./components/PostListSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanField: typeof import('vant/es')['Field']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
  }
}
